sudo: false

language: node_js
node_js:
  - "6.6.0"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - openjdk-7-jdk
    - lib32stdc++6
    - lib32z1
env:
  CXX=g++-4.8

install:
  - npm install -g process-nextick-args util-deprecate
  - npm install karma karma-jasmine jasmine-core karma-phantomjs-launcher --save-dev
  - npm install -g gulp bower cordova ionic karma-cli
  - npm install
# - bower install angular-mocks --save-dev
  - bower update

before_script:
  - wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz
  - tar -xvf android-sdk_r24.4-linux.tgz
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-23.0.2
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-23
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2
  - cd client/Blockup

script:
  - npm install
  - grunt test
  - ionic platform remove android
  - ionic platform add android
  - ionic build android --device --release
  - ls ionic info
notifications:
  email:
    recipients:
      - pahakalle@protonmail.com

#after_success:
#  - "curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge"
#  - "chmod a+x /tmp/travis-automerge"
#  - "BRANCHES_TO_MERGE_REGEX='^feature/' BRANCH_TO_MERGE_INTO=develop GITHUB_REPO=pahakalle/blockup /tmp/travis-automerge"
